import { signIn } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

function Login({providers}) {
  return (
    <>
    <Head>
        <title>Memer | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./memer.png" />
        <link rel="icon" type="image/png" href="./memer.png" />
      </Head>
    <div className='text-white flex flex-col items-center space-y-20 pt-48'>
      <Image src='/memer.png' width={150} height={150}/>
      <p>Hey guys login!</p>
      <div className=''>
        {Object.values(providers).map(provider => (
          <div key={provider.name}>
           <button onClick={() => signIn(provider.id,{callbackUrl:'/'})} href="#_" class="rounded relative inline-flex group items-center justify-center px-3.5 py-2 m-1 cursor-pointer border-b-4 border-l-2 active:border-blue-600 active:shadow-none shadow-lg bg-gradient-to-tr from-blue-600 to-blue-500 border-blue-700 text-white">
<span class="absolute w-0 h-0 transition-all duration-300 ease-out bg-white rounded-full group-hover:w-12 group-hover:h-12 opacity-10"></span>
<span class="relative">Sign in with {provider.name}</span>
</button>
          </div>
        ))}
      </div>
    </div>
    </>
  )
}

export default Login